### ISSUE TITLE
Bài tập làm 7/2 nộp bài  

### ISSUE THREAD

**Issue by htcvtc59** [htcvtc59/project#3]
@dominhnhien1997  M tìm cho t giao diện phần email xác thực . Khi t đăng kí t muốn có 1 trang gửi về khách hàng thì m tìm cho t phần xác thực email . Khi mà khách hàng click vào link trong email nó đưa đến trang reset password  thêm trang này nữa . 

@kensoloko A tìm cái y như trên e xem ai đẹp hơn e lấy 

Yêu cầu là
```
1. Page email xác thực 
2. Page thay đổi mật khẩu có input password và confirm password
 ```

**Comment by kensoloko** [comment]
Ok
